language: rust

env:
  global:
    - secure: T5QAWcRSSdFlr/Rk+xGgXoOdOMFy2/x0t5npkD+X466jwv7SDT6GXngvbAntGSJfKc33/NqJPJ3sQP0BgZ6lU3Axk1VO/Z/cubnKXdq97F0eyMj4v3/zpBlTSl0z5vD6m/KTviq0Cd1Vz2mPa5gwu+PpVvUTq/gYvKASmj61bGw=

install:
  # Required to create virtual serial ports for testing
  - sudo apt-get install -qq socat

script:
  - apt-cache show libc6 | grep Version
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
