language: rust

env:
  global:
    - secure: nB7gd+4K/yZXs/3NiCIVctpQ6QRxLrE2N0zMNnDih5tgwxmLfbJCt2FXGEhzbQ2oQlM56g5shxLNbpOVjB8/Sk9KSBZl5cURJibY+oEaJODs8ycDV7kdyjkHYLaDq7KhYQR4QbYdy8DAOvlZfV3pFpYqKGBdepeZ6mAlZIX3qzs=

install:
  # Required to create virtual serial ports for testing
  - sudo apt-get install -qq socat

script:
  - apt-cache show libc6 | grep Version
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
